# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: EMUFest 2016 Submission Form
email: info@emufest.org
description:
baseurl: "/semuform" # the subpath of your site, e.g. /blog
url: "http://www.emufest.org" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown

# Contact form
api_token: ffa37a6e8dfbed6be0247b81d0a01e3e
